### ISSUE TITLE
I need a basic config to start this plugin

### ISSUE THREAD

**Issue by ertwro** [arakkkkk/kanban.nvim#19]
after I add the plugin to packer, i try to activate it by doing:

```require('kanban').setup()```

and this is what I get

```Error detected while processing /home/ertwr/.config/nvim/lua/kickstart/init.lua:
E5113: Error while calling lua chunk: .../site/pack/packer/start/kanban.nvim/lua/kanban/utils.lua:28: bad argument #1 to 'pairs' (table
expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        .../site/pack/packer/start/kanban.nvim/lua/kanban/utils.lua:28: in function 'tableMerge'
        ...im/site/pack/packer/start/kanban.nvim/lua/kanban/ops.lua:111: in function 'get_ops'
        ...e/nvim/site/pack/packer/start/kanban.nvim/lua/kanban.lua:9: in function 'setup'
        /home/ertwr/.config/nvim/lua/kickstart/init.lua:448: in main chunk```

**Comment by arakkkkk** [comment]
Fixed, thanks for the report!

**Comment by ertwro** [comment]
I'm sorry. I didn't make myself understood. Your page lacks a simple configuration in order to make the Kanban plugin functional from the get go. The video from the terminal is not enough.
example: even if I add a configuration in the setup function after requiring the plugin. When I try to open a file or add a task something like this will happen:

```Error executing Lua callback: ...k/packer/start/kanban.nvim/lua/kanban/fn/tasks/utils.lua:17: attempt to index field 'items' (a nil value)
stack traceback:
        ...k/packer/start/kanban.nvim/lua/kanban/fn/tasks/utils.lua:17: in function 'get_focus'
        ...ack/packer/start/kanban.nvim/lua/kanban/fn/tasks/add.lua:6: in function 'add'
        ...k/packer/start/kanban.nvim/lua/kanban/create_command.lua:80: in function <...k/packer/start/kanban.nvim/lua/kanban/create_com
mand.lua:76>```

**Comment by arakkkkk** [comment]
Thank you.
However, I was not able to reproduce the error, can you give me more details about the file you are trying to open?

**Comment by ertwro** [comment]
This is the file am trying to open:

```
---

kanban-plugin: basic

---

# Template kanban


## TODO

- [ ] [[sample]]
@{2023/05/01}
#tag0


## Work in progress

- [ ] [[sample task]]
@{2023/05/01}
#tag1


## Done

- [ ] [[sample done]]
@{2023/05/01}
#tag3


## Archive

- [ ] [[sample archive]]
@{2023/05/01}
#tag4



%% kanban:settings
'```
{"kanban-plugin":"basic"}
'```
%%
```

Since `:KanbanCreate` is a nonexistent function, I created the file using the template provided here. When I try to open the file with `KanbanOpen ~/template.md` it tells me sometimes :

`Kanban is already active!!`
but no kanban is visible


```
Error executing Lua callback: .../packer/start/kanban.nvim/lua/kanban/markdown/reader.lua:53: attempt to index local 'task' (a nil value
)
stack traceback:
        .../packer/start/kanban.nvim/lua/kanban/markdown/reader.lua:53: in function 'read'
        ...e/nvim/site/pack/packer/start/kanban.nvim/lua/kanban.lua:63: in function <...e/nvim/site/pack/packer/start/kanban.nvim/lua/ka
nban.lua:31>
```

and if I do `:KanbanClose` it shows me this:

```
Error executing Lua callback: .../packer/start/kanban.nvim/lua/kanban/markdown/reader.lua:53: attempt to index local 'task' (a nil value
)
stack traceback:
        .../packer/start/kanban.nvim/lua/kanban/markdown/reader.lua:53: in function 'read'
        ...e/nvim/site/pack/packer/start/kanban.nvim/lua/kanban.lua:63: in function <...e/nvim/site/pack/packer/start/kanban.nvim/lua/ka
nban.lua:31>
```

but funnily enough sometimes it shows me the Kanban after doing `:KanbanClose`.

I do assume this is a setup problem form my part but since there's no default configuration I'm stuck.

**Comment by arakkkkk** [comment]
Thanks for all the details!
I still do not know the cause of the error. However, the implementation of :KanbanCreate is complete and available in my environment.
Maybe the installation method is the cause, how are you performing the installation?

**Comment by arakkkkk** [comment]
For the record, we have released the latest version as v1.1.
There is a possibility that updating the plugin will resolve the error.

**Comment by ertwro** [comment]
Kind of. The part when sometimes it show Kanban is already active but doesn't show anything happens from time to time and I need to restart nvim. Anyway, awesome plugin and since most of the errors are gone after updating I'm closing this. Thanks!

**Comment by arakkkkk** [comment]
We'll check on that error and fix it as we go!
Thank you!
