### ISSUE TITLE
Modifications added to the corresponding markdown(`<CR>`) got overwritten by the auto-generated timestamp of kanban.nvim

### ISSUE THREAD

**Issue by nyngwang** [arakkkkk/kanban.nvim#21]
As title. This looks like a serious bug to me, since users' data will be lost after minutes of editing.

https://user-images.githubusercontent.com/24765272/222982482-4b169b7f-1d1e-4781-bc8c-6b1df40f58ce.mov

**Comment by arakkkkk** [comment]
Thanks for spotting a serious error!!

I want to implement headers that are created more flexibly.
However for the time being, I have resolved the error by making the header created only when the page is first opened.

3f5d8d5bc9995d4388d2f440b1623ef3ab764a96
