### ISSUE TITLE
I would be great if you could save all markdown files into the a specified folder/path under the current directory.

### ISSUE THREAD

**Issue by nyngwang** [arakkkkk/kanban.nvim#22]
As title. I found it hard to identify what are those markdown files created by kanban.nvim. I also noticed that one of the markdown is stored as `.md` when the title is missing. It will be great to prevent saving markdown without a title instead.

Sorry for creating many issues within minutes, but I can promise that resolving these issues will increase the UX a lot. Thanks for creating this plugin, it's really useful regardless of these issues!

<img src="https://user-images.githubusercontent.com/24765272/222982860-b2097aac-73c8-45d8-abda-2da96263aabc.png" width="500">

**Comment by arakkkkk** [comment]
Thank you for creating the issue!!
I am glad you like it!
We will investigate and correct the issue of a file named .md being created.
Also, for the file to be created, it is possible to write as follows.
````
require("kanban").setup({
		markdown = {
			description_folder = "<path-to-save>"
})
```

**Comment by nyngwang** [comment]
> Also, for the file to be created, it is possible to write as follows. [...code]

Thank you very much, I overlooked that part of the source code. (sorry...)

> I am glad you like it!

I absolutely like it! I used to be a user of trello and you basically created that in Neovim.

> We will investigate and correct the issue of a file named .md being created.

Take your pace as I'm not in a hurry for the fix.

**Comment by arakkkkk** [comment]
Thank you for response!!

Fixes for .md have been completed!!

In addition, we have added instructions to the README on how to set up saving files thank you!! 
https://github.com/arakkkkk/kanban.nvim/commit/a05877eecb42e920160e341008b8ba97fcb67ed0
