### ISSUE TITLE
no buftype

### ISSUE THREAD

**Issue by cxwx** [arakkkkk/kanban.nvim#32]
E382: Cannot write, 'buftype' option is set

**Comment by KyleKing** [comment]
I have the same issue. Did you find a resolution?

**Comment by arakkkkk** [comment]
@cxwx @KyleKing 
Fixed. Thank you for the report.

**Comment by arakkkkk** [comment]
Great work! I'm thrilled to see it being used. Please feel free to reach out if you have any requests or suggestions!
